export const DATA_LOADER_LOADING = 'DATA_LOADER_LOADING';
export const DATA_LOADER_COMPLETED = 'DATA_LOADER_COMPLETED';
export const DATA_LOADER_ERROR = 'DATA_LOADER_ERROR';

export const ADD_ALL_USERS = 'ADD_ALL_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
